#!/bin/bash

sleep 1

# get load averages
#IFS=" " read LOAD1 LOAD5 LOAD15 <<<$(awk '{ print $1,$2,$3 }' /proc/loadavg)
LOAD_CPU=$(cut -d '.' -f 1 /proc/loadavg)
TEMP_CPU=$(cut -c -2 /sys/class/hwmon/hwmon0/temp1_input)
# get free memory
IFS=" " read USED AVAIL TOTAL <<<$(free --mega |  awk '/Mem/{print $3,$7,$2}')
# get gpu stats
LOAD_GPU=$(nvidia-smi --query-gpu=utilization.gpu --format=csv | awk 'FNR==2{print $1}')
TEMP_GPU=$(nvidia-smi --query-gpu=temperature.gpu --format=csv | awk 'FNR==2{print $1}')
# get processes
#PROCESS=`ps -eo user=|sort|uniq -c | awk '{ print $2 " " $1 }'`
#PROCESS_ALL=`echo "$PROCESS"| awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`
#PROCESS_ROOT=`echo "$PROCESS"| grep root | awk {'print $2'}`
#PROCESS_USER=`echo "$PROCESS"| grep -v root | awk {'print $2'} | awk '{ SUM += $1} END { print SUM }'`
# get processors
#PROCESSOR_NAME=`grep "model name" /proc/cpuinfo | cut -d ' ' -f3- | awk {'print $0'} | head -1`
#PROCESSOR_COUNT=`grep -ioP 'processor\t:' /proc/cpuinfo | wc -l`
USERS=$(users | sed -e 's/ /\n/g' | sort | uniq | tr '\n' ' ')

W="\e[0;39m"
G="\e[1;32m"

echo -e "
${W}system info:
$W  Uptime........: $W`uptime -p`
$W  CPU Load......: $G$LOAD_CPU${W}% ${G}$TEMP_CPU${W}°C
$W  GPU Load......: $G$LOAD_GPU${W}% ${G}$TEMP_GPU${W}°C
$W  Memory........: $G$USED${W}/$G$TOTAL${W} MB$W
$W  Logged In.....: $G$USERS$W"
